version: "3.8"

services:
  # CEB Agent (Ceylon Electricity Board)
  ceb-agent:
    build:
      context: .
      dockerfile: Dockerfile.ceb
    container_name: govpulse-ceb
    ports:
      - "10010:10010"
    environment:
      - OPEN_API_KEY=${OPEN_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY:-}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT:-GovPulse}
    networks:
      - govpulse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Health Agent (Ministry of Health)
  health-agent:
    build:
      context: .
      dockerfile: Dockerfile.health
    container_name: govpulse-health
    ports:
      - "10011:10011"
    environment:
      - OPEN_API_KEY=${OPEN_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY:-}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT:-GovPulse}
    networks:
      - govpulse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10011/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Host Agent (Main Orchestrator)
  host-agent:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: govpulse-host
    ports:
      - "11000:11000"
    environment:
      - OPEN_API_KEY=${OPEN_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY:-}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT:-GovPulse}
      - CEB_AGENT_URL=http://ceb-agent:10010
      - HEALTH_AGENT_URL=http://health-agent:10011
    depends_on:
      - ceb-agent
      - health-agent
    networks:
      - govpulse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  govpulse-network:
    driver: bridge
    name: govpulse-network

volumes:
  agent-data:
    driver: local
